spring:
  profiles: dev

db-service:
  dbname: sqlserver
  password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
---
spring:
  profiles: prod

db-service:
  dbname: oracleserver
  password: oracle


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/